name: Docker Image CI

on:
  push:
    branches: [main]

jobs:
  versionize:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.MajorMinorPatch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          useConfigFile: true

  build-container-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile infrastructure
        uses: Azure/cli@v1
        with:
          inlineScript: az bicep build --file ./templates/azure-container-app.bicep

  publish-bicep:
    runs-on: ubuntu-latest
    needs: [versionize, build-container-app]
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PROD }}
      - name: Publish
        uses: Azure/cli@v1
        with:
          inlineScript: az bicep publish --file ./templates/azure-container-app.bicep --target "br:${{ secrets.ACR_LOGIN_SERVER }}/templates/containerapp:${{needs.versionize.outputs.semver}}"
